### ISSUE TITLE
New-AzSentinelHuntingRule cmdlet fails when updating rule

### ISSUE THREAD

**Issue by javiersoriano** [wortell/AZSentinel#114]
When using New-AzSentinelHuntingRule to update an existing Hunting Rule, command fails with following error:

InvalidOperation: C:\Users\jasorian\Documents\PowerShell\Modules\AzSentinel\0.6.9\AzSentinel.psm1:1278
Line |
1278 |              $compareResult = [PSCustomObject]$compareResult1 + [PSCus …
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Method invocation failed because [System.Management.Automation.PSObject] does not contain a method named 'op_Addition'.

**Comment by javiersoriano** [comment]
I'm using the same command you are using (I'm using 0.6.9). Get works fine, but updating fails:

`PS C:\Users\jasorian> Get-AzSentinelHuntingRule -WorkspaceName sorisentinel -RuleName HuntingRule01

Category    : Hunting Queries
DisplayName : HuntingRule01
Query       : SecurityEvent | where EventID == "4688" | where CommandLine contains "-noni -ep bypass $"
Tags        : {@{Name=description; Value=test}, @{Name=tactics; Value=Persistence,LateralMovement,Exfiltration}, @{Name=createdBy; Value=}, @{Name=createdTimeUtc; Value=}}
Version     : 2
name        : 67c2a96e-0065-4a7a-aed2-a96ea3ec50e1
id          : subscriptions/1186543f-81e7-4a2c-ad55-fae1cc1c9eac/resourceGroups/sentinel/providers/Microsoft.OperationalInsights/workspaces/sorisentinel/savedSearches/67c2a96e-0065-4a7a-aed2-a96ea3ec50e1
etag        : W/"datetime'2020-10-01T07%3A52%3A20.7677333Z'"


PS C:\Users\jasorian> New-AzSentinelHuntingRule -WorkspaceName sorisentinel -DisplayName HuntingRule01 -Description "some extra" -Query "SecurityEvent" -Tactics Collection, CredentialAccess
InvalidOperation: C:\Users\jasorian\Documents\PowerShell\Modules\AzSentinel\0.6.9\AzSentinel.psm1:1278
Line |
1278 |              $compareResult = [PSCustomObject]$compareResult1 + [PSCus …
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Method invocation failed because [System.Management.Automation.PSObject] does not contain a method named 'op_Addition'.

Hunting rule HuntingRule01 is compliance, nothing to do

Name                           Value
----                           -----
Category                       Hunting Queries
Query                          SecurityEvent
DisplayName                    HuntingRule01
Tags                           {description, tactics, createdBy, createdTimeUtc}

PS C:\Users\jasorian> Get-Module AzSentinel

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     0.6.9                 AzSentinel                          {Add-AzSentinelIncidentComment, Disable-AzSentinelAlertRule, Enable-AzSentinelAlertRule, Get-AzSentinelAlertRule…}
`

**Comment by NatIC0** [comment]
I'm facing the same issue.
Issue arose while testing the sentinel-devops deployment.

**********************
PowerShell transcript start
Start time: 20201217162400
Username: ACCESS-IT\137.BLavoie.26
RunAs User: ACCESS-IT\137.BLavoie.26
Configuration Name: 
Machine: BLAVOIE-LT1 (Microsoft Windows NT 10.0.19042.0)
Host Application: C:\Program Files\PowerShell\7\pwsh.dll -WorkingDirectory ~
Process ID: 18616
PSVersion: 7.1.0
PSEdition: Core
GitCommitId: 7.1.0
OS: Microsoft Windows 10.0.19042
Platform: Win32NT
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.0.0, 6.1.0, 6.2.0, 7.0.0, 7.1.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
WSManStackVersion: 3.0
**********************
Transcript started, output file is C:\Users\137.blavoie.26\Documents\azsentinel_bug.txt
PS C:\Users\137.blavoie.26\c0dz\ga.ctoc.operations\ctoc-Intune> Get-AzSentinelHuntingRule -WorkspaceName gactoc-test -RuleName HuntingRule01

Category    : Hunting Queries
DisplayName : HuntingRule01
Query       : SecurityEvent | where EventID == "4687" | where CommandLine contains "-noni -ep bypass $"
Tags        : {@{Name=description; Value=test}, @{Name=tactics; Value=Persistence,LateralMovement,Exfiltration}, @{Name=createdBy; Value=}, @{Name=createdTimeUtc;
              Value=}}
Version     : 2
name        : 9fd142ca-f9d2-4781-a3da-397470f43278
id          : subscriptions/0d847f98-2caf-4e6f-9cde-65720df5268b/resourceGroups/gactoc-test/providers/Microsoft.OperationalInsights/workspaces/gactoc-test/savedSearche
              s/9fd142ca-f9d2-4781-a3da-397470f43278
etag        : W/"datetime'2020-12-16T14%3A57%3A58.8731816Z'"


PS C:\Users\137.blavoie.26\c0dz\ga.ctoc.operations\ctoc-Intune> New-AzSentinelHuntingRule -WorkspaceName gactoc-test -DisplayName HuntingRule01 -Description "some extra" -Query "SecurityEvent" -Tactics Collection, CredentialAccess

InvalidOperation: C:\Users\137.blavoie.26\Documents\PowerShell\Modules\AzSentinel\0.6.16\AzSentinel.psm1:1381
Line |
1381 |              $compareResult = [PSCustomObject]$compareResult1 + [PSCus …
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Method invocation failed because [System.Management.Automation.PSObject] does not contain a method named 'op_Addition'.

[91mInvalidOperation: [0mC:\Users\137.blavoie.26\Documents\PowerShell\Modules\AzSentinel\0.6.16\AzSentinel.psm1:1381
[96mLine |
[96m1381 | [0m             [96m$compareResult = [PSCustomObject]$compareResult1 + [PSCus[0m …
[96m     | [91m             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[91m[96m     | [91mMethod invocation failed because [System.Management.Automation.PSObject] does not contain a method named 'op_Addition'.
[0m
Hunting rule HuntingRule01 is compliance, nothing to do

Name                           Value
----                           -----
Query                          SecurityEvent
DisplayName                    HuntingRule01
Category                       Hunting Queries
Tags                           {description, tactics, createdBy, createdTimeUtc}

PS C:\Users\137.blavoie.26\c0dz\ga.ctoc.operations\ctoc-Intune> Get-Module AzSentinel

ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     0.6.16                AzSentinel                          {Add-AzSentinelIncidentComment, Disable-AzSentinelAlertRule, Enable-AzSentinelAlertRule, Export-A…

PS C:\Users\137.blavoie.26\c0dz\ga.ctoc.operations\ctoc-Intune> Stop-Transcript
**********************
PowerShell transcript end
End time: 20201217162429
**********************
