### ISSUE TITLE
Guidance: How to change the displayName of an alert?

### ISSUE THREAD

**Issue by sbroosnokia** [wortell/AZSentinel#29]
I tried to rename an alert by specifying "name" (the alert id) and displayName: the alert name. But I get an error when I change displayName to something else (Add-Member : Cannot add a member with the name "DisplayName" because a member with that name already exists. To overwrite the member anyway, add the Force parameter to your command.)

It then proceeds, but just creates a new instance of the new alert. The wanted behavior would be: rename the alert.

**Comment by pkhabazi** [comment]
hi @sbroosnokia thanks for the feedback, this is currently not available in the AzSentinel module. the problem is that we use displayName as the unique identifier for the compare function. otherwise we cannot test if the alert rule already exists. we ca do 2 thinks to solve this issue:
1. we can introduce a new field in JSON layout for example "displayNameNew" and when this is filled in we will have the old and new name at the same time to make the compare and rename. but this means after the run you need to update the JSON and change "displayName" and "displayNameNew" values, otherwise the second time you will get a conflict..
2. option two is to introduce a new cmdlet dedicated for renaming the alertRules, something like Rename-AzSentinelAlertRule -workspace "Workspace name" -AlertRuleName "Rule name" - NewAlertRuleName "NewRuleName". I think this one is cleaner but then you cannot use it in "import-azsentinelAlertRule" for example because you don't have the reference..

please let me know what you think about the proposed solutions.

Kind regards,
Pouyan

**Comment by sbroosnokia** [comment]
Hi,

Second solution is much cleaner according to me. The reason for this request is because we check in our alert rules in git, and do a scripted synchronize once all ci testing is done. Currently this will create multiple rules when the title of the rule got changed.

Could it be a possibility to work with a uuid as identifier? I think Microsoft does it for the official rules as well.
