### ISSUE TITLE
Alert Aggregation

### ISSUE THREAD

**Issue by jaroslavkozak** [wortell/AZSentinel#57]
# Summary of the new feature/enhancement

**_Enhancement / Question_**

Is there ETA for setting Alert Aggregation using New-AZSentinelAlertRule or Import-AzSentinelAlertRule?

**Comment by pkhabazi** [comment]
Thanks for the feedback, it's on my backlog. I hope that we can have at least part of it finished next week.

**Comment by pkhabazi** [comment]
To give you a status update, I have the alert aggregation with all the properties working in the current PR. unfortunately I am having some issues with the compare functionality which breaks due to the multiple layers. you can import the module from this branch manually if you need this functionality asap and ignore the compare result.

**Comment by kay07949** [comment]
Will this be finalised anytime soon?

**Comment by kay07949** [comment]
will this be finalised any time soon?
