### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by secure0** [wortell/AZSentinel#60]
How can we set the following parameters for a Sentinel alert rule ( type scheduled) using AZSentinel module ?

1) incidentConfiguration     (i.e CreateIncident = True)

2) queryResultsAggregationSettings

**Comment by pkhabazi** [comment]
To give you a status update, I have the alert aggregation with all the properties working in the current PR. unfortunately I am having some issues with the compare functionality which breaks due to the multiple layers. you can import the module from this branch manually if you need this functionality asap and ignore the compare result.
